spring:
  datasource:
    url: jdbc:sqlite:E:src/main/resources/database.sql
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.yank.sqlite:sqlite-dialect:1.0.0

