name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build_application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build MySQL Server
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
      - run: mysql --host localhost -uroot -e 'SELECT version()'

      # Set up JDK for Gradle
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Set up Node.js for npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Clean npm directories and install dependencies
      - name: Clean npm directories
        run: |
          rm -rf node_modules
          rm -rf dist
          rm -rf build

      - name: Install npm dependencies
        run: npm install

      # Set up MySQL
      - name: Create MySQL database
        run: |
          mysql -uroot -e "CREATE DATABASE marketplace_database;"
          mysql -uroot -D marketplace_database -e "CREATE TABLE player (player_name varchar(30) NOT NULL, inventory_space INT NOT NULL, day INT NOT NULL, money decimal(10, 2) NOT NULL);"
          mysql -uroot -D marketplace_database -e  "CREATE TABLE high_score (player_name VARCHAR(30) NOT NULL, score INT NOT NULL);"
          mysql -uroot -D marketplace_database -e  "CREATE TABLE inventory (item_name TEXT NOT NULL, amount INT NOT NULL);"
          mysql -uroot -D marketplace_database -e  "CREATE TABLE items (item_name TEXT NOT NULL, image_url TEXT NOT NULL, price DECIMAL(10, 2) NOT NULL);"
          mysql -uroot -D marketplace_database -e  "INSERT INTO items (item_name, image_url, price)
          VALUES
          ('Bread', '/assets/items/bread.png', 2.0),
          ('Steak', '/assets/items/steak.png', 4.0),
          ('Cheese', '/assets/items/cheese.png', 5.0),
          ('Mead', '/assets/items/mead.png', 12.0),
          ('Apple', '/assets/items/apple.png', 3.0),
          ('Pickaxe', '/assets/items/pickaxe.png', 10.0),
          ('Journal', '/assets/items/journal.png', 8.0),
          ('Fire Starter', '/assets/items/fire_starter.png', 3.0),
          ('Bucket', '/assets/items/bucket.png', 4.0),
          ('Rope', '/assets/items/rope.png', 6.0),
          ('Sword', '/assets/items/sword.png', 50.0),
          ('Bow', '/assets/items/bow.png', 30.0),
          ('Arrows', '/assets/items/arrows.png', 15.0),
          ('Chest Plate', '/assets/items/chest_plate.png', 25.0),
          ('Iron Helmet', '/assets/items/iron_helmet.png', 20.0),
          ('Healing Potion', '/assets/items/healing_potion.png', 18.0),
          ('Elixir', '/assets/items/elixir.png', 25.0),
          ('Herbs', '/assets/items/herbs.png', 7.0),
          ('Antidote Potion', '/assets/items/antidote_potion.png', 16.0),
          ('Tea', '/assets/items/tea.png', 5.0),
          ('Cloak', '/assets/items/cloak.png', 22.0),
          ('Boots', '/assets/items/boots.png', 12.0),
          ('Silver Ring', '/assets/items/silver_ring.png', 20.0),
          ('Tunic', '/assets/items/tunic.png', 8.0),
          ('Hat', '/assets/items/hat.png', 10.0),
          ('Crystal Orb', '/assets/items/crystal_orb.png', 60.0),
          ('Spell Scroll', '/assets/items/spell_scroll.png', 45.0),
          ('Amulet', '/assets/items/amulet.png', 80.0),
          ('Mysterious Dust', '/assets/items/mysterious_dust.png', 40.0),
          ('Dragon Scale', '/assets/items/dragon_scale.png', 100.0);"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Clean and build the Gradle project
      - name: Clean and build Gradle project
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW:

        run: |
          ./gradlew clean build

