name: CI

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - main

jobs:
  build_application:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build MySQL Server
        uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
      - run: mysql --host localhost -uroot -e 'SELECT version()'

      # Set up JDK for Gradle
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Set up Node.js for npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Clean npm directories and install dependencies
      - name: Clean npm directories
        run: |
          rm -rf node_modules
          rm -rf dist
          rm -rf build

      - name: Install npm dependencies
        run: npm install

      # Set up MySQL
      - name: Create MySQL database
        run: |
          mysql -uroot -e "CREATE DATABASE marketplace_database;"
          mysql -uroot -D marketplace_database -e "CREATE TABLE player (player_name varchar(30) NOT NULL, money decimal(10, 2) NOT NULL, inventory_space INT NOT NULL, inventory_items JSON, day INT NOT NULL);"
          mysql -uroot -D marketplace_database -e "SHOW TABLES;"

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # Clean and build the Gradle project
      - name: Clean and build Gradle project
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PW:

        run: |
          ./gradlew clean build

